'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FrmEntryKaryawan

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''ErrMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrMsg As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''PopupControlContentControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlContentControl1 As Global.DevExpress.Web.PopupControlContentControl

    '''<summary>
    '''LblErr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblErr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BtnClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnClose As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopEntKeluarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopEntKeluarga As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''PopupControlContentControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlContentControl2 As Global.DevExpress.Web.PopupControlContentControl

    '''<summary>
    '''TxtActKeluarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtActKeluarga As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtNoUrutKeluarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNoUrutKeluarga As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtHubKeluarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHubKeluarga As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''TxtNamaKeluarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNamaKeluarga As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtJenisKelaminKeluarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJenisKelaminKeluarga As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''TxtTglLahirKeluarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTglLahirKeluarga As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtPekerjaanKeluarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPekerjaanKeluarga As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtPerusahaanKeluarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPerusahaanKeluarga As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''BtnSaveKeluarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSaveKeluarga As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''BtnCancelKeluarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancelKeluarga As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopEntPendidikan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopEntPendidikan As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''PopupControlContentControl3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlContentControl3 As Global.DevExpress.Web.PopupControlContentControl

    '''<summary>
    '''TxtActPendidikan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtActPendidikan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtNoUrutPendidikan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNoUrutPendidikan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtTgkPendidikan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTgkPendidikan As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''TxtPrdAwalPendidikan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAwalPendidikan As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtPrdAkhirPendidikan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAkhirPendidikan As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtInstitusiPendidikan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtInstitusiPendidikan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtAlamatInstitusiPendidikan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAlamatInstitusiPendidikan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtJurusanPendidikan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJurusanPendidikan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtLlsTdkLlsPendidikan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLlsTdkLlsPendidikan As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''TxtNilaiPendidikan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNilaiPendidikan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtNoIjazahPendidikan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNoIjazahPendidikan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''BtnSavePendidikan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSavePendidikan As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''BtnCancelPendidikan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancelPendidikan As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopEntKetrampilan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopEntKetrampilan As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''PopupControlContentControl4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlContentControl4 As Global.DevExpress.Web.PopupControlContentControl

    '''<summary>
    '''TxtActKetrampilan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtActKetrampilan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtNoUrutKetrampilan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNoUrutKetrampilan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtNamaKetrampilan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNamaKetrampilan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtPrdAwalKetrampilan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAwalKetrampilan As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtPrdAkhirKetrampilan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAkhirKetrampilan As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtNamaSertifikatKetrampilan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNamaSertifikatKetrampilan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtGradeKetrampilan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtGradeKetrampilan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtNoSertifikatKetrampilan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNoSertifikatKetrampilan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtInstitusiKetrampilan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtInstitusiKetrampilan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''BtnSaveKetrampilan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSaveKetrampilan As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''BtnCancelKetrampilan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancelKetrampilan As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopEntRwytPekerjaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopEntRwytPekerjaan As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''PopupControlContentControl5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlContentControl5 As Global.DevExpress.Web.PopupControlContentControl

    '''<summary>
    '''TxtActRwytPekerjaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtActRwytPekerjaan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtNoUrutRwytPekerjaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNoUrutRwytPekerjaan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtPrdAwalRwytPekerjaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAwalRwytPekerjaan As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtPrdAkhirRwytPekerjaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAkhirRwytPekerjaan As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtPerusahaanRwytPekerjaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPerusahaanRwytPekerjaan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtAlamatRwytPekerjaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAlamatRwytPekerjaan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtIndustriRwytPekerjaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtIndustriRwytPekerjaan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtJabatanRwytPekerjaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJabatanRwytPekerjaan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtLokasiKerjaRwytPekerjaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLokasiKerjaRwytPekerjaan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtGajiRwytPekerjaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtGajiRwytPekerjaan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtTunjanganRwytPekerjaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTunjanganRwytPekerjaan As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''TxtUraianRwytPekerjaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtUraianRwytPekerjaan As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''BtnSaveRwytPekerjaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSaveRwytPekerjaan As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''BtnCancelRwytPekerjaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancelRwytPekerjaan As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopEntRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopEntRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''PopupControlContentControl6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlContentControl6 As Global.DevExpress.Web.PopupControlContentControl

    '''<summary>
    '''TxtActRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtActRwytPekerjaanMinarta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtNoUrutRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNoUrutRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtPrdAwalRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAwalRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtPrdAkhirRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAkhirRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtDivisiRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDivisiRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtSubdivisiRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSubdivisiRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtLokasiKerjaRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLokasiKerjaRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtJabatanRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJabatanRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtGolonganRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtGolonganRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtGradeRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtGradeRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtGajiRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtGajiRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtTunjanganRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTunjanganRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''TxtKPIRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtKPIRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtTesKesehatanRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTesKesehatanRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''TxtHasilKesehatanRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHasilKesehatanRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''TxtTesPsikologiRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTesPsikologiRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''TxtHasilPsikologiRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHasilPsikologiRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''TxtAtasanRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAtasanRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtUraianRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtUraianRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''BtnSaveRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSaveRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''BtnCancelRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancelRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''LblAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblAction As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BtnSaveDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSaveDataEntry As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''BtnCancelDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancelDataEntry As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''TxtNIK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNIK As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtNoKTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNoKTP As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtNama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNama As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtPrdAwalKTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAwalKTP As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtPrdAkhirKTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAkhirKTP As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''RblJenisKelamin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RblJenisKelamin As Global.DevExpress.Web.ASPxRadioButtonList

    '''<summary>
    '''TxtDiterbitkanOlehKTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDiterbitkanOlehKTP As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtTempatLahir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTempatLahir As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtTanggalLahir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTanggalLahir As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtNoPassport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNoPassport As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtWN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtWN As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtPrdAwalPassport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAwalPassport As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtPrdAkhirPassport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAkhirPassport As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''UpdPanelStsNikah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdPanelStsNikah As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''RblStsNikah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RblStsNikah As Global.DevExpress.Web.ASPxRadioButtonList

    '''<summary>
    '''TxtTglNikah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTglNikah As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtDiterbitkanOlehPassport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDiterbitkanOlehPassport As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''RblAgama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RblAgama As Global.DevExpress.Web.ASPxRadioButtonList

    '''<summary>
    '''TxtNoNPWP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNoNPWP As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''DDLDivisi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLDivisi As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''TxtPrdAwalNPWP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAwalNPWP As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtPrdAkhirNPWP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAkhirNPWP As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtSubdivisi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSubdivisi As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtDiterbitkanOlehNPWP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDiterbitkanOlehNPWP As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtJabatan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJabatan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtNoKK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNoKK As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtGolongan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtGolongan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtPrdAwalKK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAwalKK As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtPrdAkhirKK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAkhirKK As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtGrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtGrade As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtDiterbitkanOlehKK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDiterbitkanOlehKK As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtPrdAwal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAwal As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtNoSIMA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNoSIMA As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtUraian control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtUraian As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''TxtPrdAwalSIMA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAwalSIMA As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtPrdAkhirSIMA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAkhirSIMA As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtAlamat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAlamat As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''TxtDiterbitkanOlehSIMA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDiterbitkanOlehSIMA As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtProvinsi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtProvinsi As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtNoSIMB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNoSIMB As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtKota control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtKota As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtPrdAwalSIMB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAwalSIMB As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtPrdAkhirSIMB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAkhirSIMB As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtAlamatSurat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAlamatSurat As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''TxtDiterbitkanOlehSIMB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDiterbitkanOlehSIMB As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEmail As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtNoSIMC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNoSIMC As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtNoTelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNoTelp As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtPrdAwalSIMC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAwalSIMC As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtPrdAkhirSIMC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrdAkhirSIMC As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtLokasiKerja control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLokasiKerja As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtDiterbitkanOlehSIMC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDiterbitkanOlehSIMC As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''PasFoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasFoto As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''PasFotoDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasFotoDefault As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''FileUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''BtnPopUpKeluarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPopUpKeluarga As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''GridDataKeluarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridDataKeluarga As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''BtnPopUpPendidikan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPopUpPendidikan As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''GridDataPendidikan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridDataPendidikan As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''BtnPopUpKetrampilan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPopUpKetrampilan As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''GridDataKetrampilan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridDataKetrampilan As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''BtnPopUpRwytPekerjaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPopUpRwytPekerjaan As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''GridDataRwytPekerjaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridDataRwytPekerjaan As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''BtnPopUpRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPopUpRwytPekerjaanMinarta As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''GridDataRwytPekerjaanMinarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridDataRwytPekerjaanMinarta As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GridDokumenPendukung control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridDokumenPendukung As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''DialogWindow1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DialogWindow1 As Global.MetaBuilders.WebControls.DialogWindow

    '''<summary>
    '''msgBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgBox1 As Global.BunnyBear.msgBox
End Class
